### ISSUE TITLE
bizarre error

### ISSUE THREAD

**Issue by nhooyr** [buildkite-plugins/docker-buildkite-plugin#100]
Trying to use this plugin but my agent is giving:

```
🚨 Error: Failed to parse a plugin definition: Configuration for "github.com/buildkite-plugins/image-buildkite-plugin" is not a hash
```

Using latest docker image.

`pipeline.yml` looks like:

```yml
steps:
- label: 'go env'
  command: go env
  plugins:
  - docker#v3.0.1:
    image: "golang:latest"
```
