### ISSUE TITLE
Add `--add-host` functionality

### ISSUE THREAD

**Issue by jahredhope** [buildkite-plugins/docker-buildkite-plugin#105]
## Feature request
Allow the consumer to pass in values to be applied with `--add-host="host:IP` to append records to `/etc/hosts`.

As described in [Docker Network settings](https://docs.docker.com/engine/reference/run/#/network-settings)

#### Suggested syntax
```yaml
  docker#v1.4.0:
    image: 'node:10.15'
    hosts:
     - 'example.com.local:127.0.0.1'
# OR
       example.com.local: '127.0.0.1'
```
