### ISSUE TITLE
Unfurl command for docker run

### ISSUE THREAD

**Issue by pecigonzalo** [buildkite-plugins/docker-buildkite-plugin#120]
Commands passed to `docker run` should be unfurled, otherwise they do not work as intended, for example the node snipped from the readme:
```
  - command:
      - "yarn install"
      - "yarn run test"
    plugins:
      - docker#v3.1.0:
          image: "node:7"
          always-pull: true
          environment:
            - "MY_SECRET_KEY"
            - "MY_SPECIAL_BUT_PUBLIC_VALUE=kittens"
```

would output:
```
yarn run test' in node:7
--
  | docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"yarn install\\nyarn run test\": executable file not found in $PATH": unknown.
  | 🚨 Error: The command exited with status 127
```

This is because its like doing:
`docker run --rm node:7 "yarn install"` instead of `docker run --rm node:7 yarn install`

Line:
https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/7c8e01ee90ebc29bb23436a52d924ecf1a2c43fa/hooks/command#L363

should probably change to

```
[...] docker run ${args[@]}
```
