### ISSUE TITLE
docker: command not found

### ISSUE THREAD

**Issue by micapam** [buildkite-plugins/docker-buildkite-plugin#15]
I'm not sure if I'm doing something wrong, or if this is an actual bug, so apologies if it's the former. 

Whatever I do, I get the error `docker: command not found`. Even if my step is something very simple, like an echo statement:

```
Running plugin github.com/buildkite-plugins/docker-buildkite-plugin#v1.1.1 command hook | 0s
-- | --
  | # Executing "/home/buildkite/.buildkite-agent/plugins/github-com-buildkite-plugins-docker-buildkite-plugin-v1-1-1/hooks/command"
  |   | Running echo 'Does this work?' . in docker:latest | 0s
  | /home/buildkite/.buildkite-agent/plugins/github-com-buildkite-plugins-docker-buildkite-plugin-v1-1-1/hooks/command: line 62: docker: command not found
```

Here is my pipeline.yml: 

```
steps: 
  - label: 'test plugin'
    command: echo 'Does this work?'
    plugins: 
      docker#v1.1.1:
        image: "docker:latest"
        mounts: 
          - /var/run/docker.sock:/var/run/docker.sock
```

I took a look at the hook script and the failing line (62) is: 

`docker run "${args[@]}" "${BUILDKITE_PLUGIN_DOCKER_IMAGE}" bash -c "${BUILDKITE_COMMAND}"`
