### ISSUE TITLE
mount-buildkite-agent on Windows fails with invalid volume specification

### ISSUE THREAD

**Issue by petemounce** [buildkite-plugins/docker-buildkite-plugin#157]
```txt
C:\Program Files\docker\docker.exe: Error response from daemon: invalid volume specification: '/c/program files/buildkite-agent/buildkite-agent:/usr/bin/buildkite-agent'.
```

Plugin version v3.5.0.

Windows 2019 Server.

**Comment by zymotik** [comment]
@petemounce did you solve this or find a workaround?

**Comment by zymotik** [comment]
Ok, I've spotted the issue, the mapping is in the Linux style for the volumes, ie:

```
docker run 
    -i 
    --rm 
    --volume C:\\buildkite-agent\\builds\\build-windows\\app:c:\\app --workdir c:\\app  
    --volume /c/buildkite-agent/bin/buildkite-agent:/usr/bin/buildkite-agent 
    --label com.buildkite.job-id=some-id
    mcr.microsoft.com/windows:1809-amd64
```

Notice the difference between the first volume mapping and the second one which is causing the failure with:

**C:\Program Files\Docker\docker.exe: Error response from daemon: invalid volume specification: '/c/buildkite-agent/bin/buildkite-agent:/usr/bin/buildkite-agent'.**

**Comment by petemounce** [comment]
My workaround was to mount the directory containing the binary into a directory in the PATH within my container via a volume, and then also -e the token for auth.

**Comment by zymotik** [comment]
Thanks @petemounce, that worked for me too. I also added the necessary env tokens:

```
  - label: "Create package"
    artifact_paths:
      - "./output/**/*"
    plugins:
      - docker#v3.5.0:
          image: mcr.microsoft.com/powershell:windowsservercore-1809
          environment:
            - BUILDKITE_JOB_ID
            - BUILDKITE_BUILD_ID
            - BUILDKITE_AGENT_ACCESS_TOKEN
          workdir: c:\app
          volumes: 
            - "c:\\buildkite-agent:c:\\buildkite-agent"
#          mount-buildkite-agent: true # This fails due to a bug, workaround is to add the volume manually
          command: ["pwsh", "build\\prepare-package.ps1"]
    agents:
      queue: build.windows
```
