### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by scottrobertson** [buildkite-plugins/docker-buildkite-plugin#18]
Hey

Installed the agent on Ubuntu 16.04, and installed docker. Getting the following:

```
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.37/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
```

```
steps:
  - command: docker build . -t image:tag
    plugins:
      docker#v1.1.1:
        image: "docker:latest"
        mounts:
          - /var/run/docker.sock:/var/run/docker.sock
```
