### ISSUE TITLE
Why doesn't `propagate-environment` include env vars set in hooks?

### ISSUE THREAD

**Issue by evandam** [buildkite-plugins/docker-buildkite-plugin#184]
Hi folks,

Just wondering what the reason/limitation is behind why setting `propagate-environment: true` does not include environment variables that are set by hooks. The current behavior is clearly documented, but I'm unsure of why since it seems like it would be a very common and useful feature to have.

For example, I would expect the following to set `GIT_SHA` correctly:

`/etc/buildkite-agent/pre-command`:

```bash
export GIT_SHA="$(git rev-parse --short HEAD)"
```

`pipeline.yml`:

```yaml
steps:
  - command: "echo $$GIT_SHA"
    env:
      FOO: bar
    plugins:
      - docker#v3.8.0:
          image: busybox
          propagate-environment: true
```

I need to pass `environment: ["GIT_SHA"]` explicitly in the plugin config for it to work. It would be helpful to include these environment variables, since a very common use of hooks is to expose environment variables to a step. It would also be very helpful in case a lot of env vars are set in hooks, and the steps don't need to keep the list in sync.
