### ISSUE TITLE
Exit codes > 1 are not correctly propagated

### ISSUE THREAD

**Issue by krfricke** [buildkite-plugins/docker-buildkite-plugin#191]
Exit codes > 1 are not propagated to buildkite, thus e.g. automatic retry triggers that depend on exit code are failing.

Pipeline:

```
steps:
  - label: ":pipeline:"
    agents:
      queue: runner_queue_branch
    plugins:
      "docker#v3.9.0":
        image: ubuntu
        propagate-environment": True
    command: exit 2
```

Output:

```

🚨 Error: The command exited with status 1
--

user command error: The plugin docker command hook exited with status 1
```

Is this an error on buildkite core or in this plugin?
