### ISSUE TITLE
Handling of parameters when shell is false

### ISSUE THREAD

**Issue by GuillermoContrerasP** [buildkite-plugins/docker-buildkite-plugin#227]
Version: v5.3.0
When using a docker image that doesn't have a shell, there is an issue when passing several parameters. Please look at the example below:
`<html><body>

$ docker run -t -i --rm --init --volume /buildkite/builds/buildkite-agent-8454df698b-qbq2d-1/bose/terraform-zonenetwork-pull-request:/workdir --workdir /workdir --label com.buildkite.job-id=01848b76-4680-4a10-a6b3-745d9cd6e37a ghcr.io/terraform-linters/tflint-bundle:latest --force\ --enable-plugin=aws
--

Failed to parse CLI options; `force --enable-plugin` is unknown option. Please run `tflint --help`
</body>
</html>`

The problem seems that the backlash character ('\') between the options is causing an issue. In my opinion, if shell is set as false, this backlash shouldn't be added.
If there is a workaround to this issue, please let me know.

Thanks in advance

**Comment by toote** [comment]
@GuillermoContrerasP that is an interesting issue, could you share the step that caused that?

**Comment by GuillermoContrerasP** [comment]
Sure thing. Here is the step definition that caused the issue:
`steps:
  - label: "Terraform linting command"
    command: "--force  --enable-plugin=aws"
    plugins:
      - docker#v5.3.0:
          image: "ghcr.io/terraform-linters/tflint-bundle:latest"
          always-pull: true
          shell: false`

**Comment by toote** [comment]
@GuillermoContrerasP quite interesting... the plugin is indeed passing the `command` string as-is, but it is a single string so it is intepreted as a single string that contains a space.

A possible workaround is to use the plugin's command to split them into an array:

```
steps:
  - label: "Terraform linting command"
    plugins:
      - docker#v5.3.0:
          image: "ghcr.io/terraform-linters/tflint-bundle:latest"
          always-pull: true
          shell: false
          command:
            - "--force"
            - "--enable-plugin=aws"
```

I'm not sure if the assumption that a lack of shell should mean that the step level command needs to be split on spaces. Will leave this ticket open and review what can be done about that use case, though.
