### ISSUE TITLE
How to pass environment variable to command?

### ISSUE THREAD

**Issue by benwen-instacart** [buildkite-plugins/docker-buildkite-plugin#248]
Similar to what we are having for `volumes`: `expand-volume-vars`, we would like to pass environment variable to `command` too.
Have tried many possible ways, like single dollar sign `$VARIABLE_NAME`, double dollar sign `$$VARIABLE_NAME`, etc, but none works.
Could you add `expand-command-vars`? Or what is the best practice to pass environment variable to `command`?

code snippet:
```
steps:
  - label: "My step"
    plugins:
      - "my/plugin#v0.0.1:
      - docker#5.6.0:
          image: "my-image"
          expand-volume-vars: true
          volumes:
            - "$$MY_VOLUME_VARIABLE_SRC:$$MY_VOLUME_VARIABLE_DST"
         command: ["./bin/my-app", "$$MY_COMMAND_VARIABLE"]
```
