### ISSUE TITLE
Next major version should support the 99% case

### ISSUE THREAD

**Issue by keithpitt** [buildkite-plugins/docker-buildkite-plugin#260]
I'd like us to revisit the decision made here: https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/164

While I 100% agree that having `propagate-environment` on by default _is_ somewhat a security issue, I think the point of this plugin is that it makes the 99% case easy mode.

All of the steps I've been writing lately have had both of these options turned on:

```
steps:
  - command: "ruby my-script.rb"
    plugins:
      - docker#v5.4.0:
          image: "ruby:latest"
          propagate-environment: true #<-- this
          mount-buildkite-agent: true #<-- and this
```

I think if folks want to go down a "secure docker" route, they have the option to call out to docker directly. But I think we should optimise this plugin for "everything just works" by default.

Are there any other options that we should consider flipping the defaults for?
