### ISSUE TITLE
Failure to pull docker image does not result in failed buil #109

### ISSUE THREAD

**Issue by thiagomata** [buildkite-plugins/docker-buildkite-plugin#279]
Very similar to https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/109

```yaml
- label: ":docker: Isolate issue"
  key: isolate-issue
  agents:
    queue: "default"
  env:
    BUILDKIT_PROGRESS: plain
  plugins:
    - docker#v5.9.0:
        image: "this-image-do-not-exists" # intentionally asking for an image that does not exist
        always-pull: true
        mount-checkout: true
        propagate-environment: true
        privileged: true
        userns: "host"
        shell: false
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/root/.config/envd:/root/.config/envd"
```

![image](https://github.com/user-attachments/assets/1fe03ef4-1193-4950-bbac-ac648b8b2392)

## Expected Behaviour

The buildkite step should fail.

## Observed Behaviour

The buildkite step concludes as a success.
