### ISSUE TITLE
environment variables passed into container?

### ISSUE THREAD

**Issue by maks** [buildkite-plugins/docker-buildkite-plugin#53]
Reading the Readme:

> and the required environment variables set

lead me to believe that all the `BUILDKITE_*` env vars would be passed into the docker container but it turns out after some debugging that is not to be the case, and only 3 vars are actually passed in:
`BUILDKITE_JOB_ID`, `BUILDKITE_BUILD_ID` and `BUILDKITE_AGENT_ACCESS_TOKEN`.

Is that the intention or as per the code in https://github.com/buildkite-plugins/docker-buildkite-plugin/blob/master/hooks/command#L44 that only the very specifically names env vars are passed into the container along with the 3 above? If thats the case it would be good to be explicit about this in the Readme.

**Comment by toolmantim** [comment]
Thanks for taking the time to file that as an issue @maks, and sorry it caused some confusion. I've just pushed an update to make it a little clearer. Do you think that should avoid future confusion?

**Comment by maks** [comment]
@toolmantim thanks that's great! Yes I think that makes it much more clear that only those 3 are passed in

**Comment by blsmth** [comment]
i'm stumbling upon this issue because i'm also confused by this functionality.  what is the reasoning behind not passing in all the env variables?    it's confusing as well that variables defined my `steps` also don't get passed through....  am i missing something?

**Comment by lox** [comment]
@blsmth I'm sorry for the confusion! We don't pass through env by default because generally docker usage requires you to opt-in to what environment is passed from the host and we try and match up with docker's philosophies as closely as possible in this plugin. 

We could certainly consider a flag that allows you to pass in all environment from the job though. Perhaps something like:

```yaml
steps:
  - command: yarn install && yarn run test
    plugins:
      docker#v1.4.0:
        image: "node:7"
        workdir: /app
        job_environment: true
```

**Comment by kimgov** [comment]
Hey there, I am also playing around with passing env vars to containers via the Docker plugin. 

I've finally got my head around how it works however just one more question I want to confirm.

If I declare an env var at the pipeline level (see example below), then it does not _export_ the variable and therefore is not usable in a shell script. This means you have to declare the ENV VAR in the job step (commented out code below)?

@lox that would be great if a flag was available as currently I'm repeatedly passing in the same bunch of BUILDKITE_* variables in every job of my pipeline

```
env:
  MYENVVAR: "hello"

steps:
  - label: ':partyparrot: Test Docker Plugin'
    command:
      - echo $MYENVVAR
      - test-env-var.sh
    plugins:
      docker#v1.4.0:
        image: alpine
#        environment:
#          - MYENVVAR=hello
```
