### ISSUE TITLE
Multiple commands don't fail pipeline on non-zero exit status

### ISSUE THREAD

**Issue by sjtyro** [buildkite-plugins/docker-buildkite-plugin#54]
If you define multiple steps in a standard BuildKite pipeline are defined, the pipeline will only pass if all of the commands return a 0 exit status. When running in the Docker plugin, we are noticing this behaviour is missing.  Here is a sample pipeline.yml for reproducing the issue:

```
steps:
  - name: "multiple command first fail bash"
    command:
      - /bin/bash -c 'exit 1'
      - /bin/bash -c 'exit 0'

  - name: "multiple command first fail docker"
    plugins:
      docker:
        always-pull: true
        image: 'ubuntu'
    command:
      - /bin/bash -c 'exit 1'
      - /bin/bash -c 'exit 0'
```

Both pipelines should fail but only the non-Docker pipeline fails.
