### ISSUE TITLE
No way to expand globs in a command

### ISSUE THREAD

**Issue by huonw** [buildkite-plugins/docker-buildkite-plugin#75]
I'm trying to use `shellcheck` to check multiple scripts in a repository, using a glob like `**/*.sh` to avoid to have an error-prone manual list of all the scripts (the same applies to `scripts/*.sh` or similar). Per the README (and #74), this needs to be done via `command`:

```yaml
steps:
  - plugins:
      docker#2d93e90397c1497a8e15a5be2bdaf7aca59af3f3:
        image: "koalaman/shellcheck"
        command: ["**/*.sh"]
```

However this fails, because the glob isn't expanded:

```
Running **/*.sh in koalaman/shellcheck:latest
**/*.sh: **/*.sh: openBinaryFile: does not exist (No such file or directory)
```

I might be misreading the documentation, but there doesn't seem to be a way to force the expansion, nor does there seem to be a way to more directly with an image like this one without just dropping the plugin entirely.
