### ISSUE TITLE
Add option for propagating all environment variables

### ISSUE THREAD

**Issue by zsims** [buildkite-plugins/docker-buildkite-plugin#79]
Per the Elastic CI for AWS guidance (https://github.com/buildkite/elastic-ci-stack-for-aws#what-type-of-builds-does-this-support):

> Each project should encapsulate it's dependencies via Docker and Docker Compose

This results in using this plugin for setting up build dependencies. It would be nice to add an option to propagate *all* environment variables to the container, e.g.

```
steps:
  - command: "echo \$BUILDKITE_COMMIT"
    plugins:
      - docker#v2.0.0:
         image: bash 
```

Rather than having to specify that `BUILDKITE_COMMIT` propagates to the container (with `environment`)

**Comment by lox** [comment]
Agreed! Any suggestions on what the syntax for that would look like? 

```yaml
steps:
  - command: "echo \$BUILDKITE_COMMIT"
    plugins:
      - docker#v2.0.0:
         image: bash
         build-environment: true
```

**Comment by zsims** [comment]
I think something like `propagate-env: true` or `include-all-env: true` or `automatic-environment: true` avoiding something like `build` as that is a bit confusing re `docker build`

```
steps:
  - command: "echo \$BUILDKITE_COMMIT"
    plugins:
      - docker#v2.0.0:
         image: bash
         propagate-env: true
```
